### PR TITLE
Update examples to v6

### LINKED ISSUE #13: Maze solver example throws an error
Running the `maze.jl` file in the `docs/examples` directory gives the following error:
```
ERROR: LoadError: promotion of types Int64 and FixedPointNumbers.N0f8 failed to change any arguments
Stacktrace:
  [1] error(::String, ::String, ::String)
    @ Base ./error.jl:42
  [2] sametype_error(input::Tuple{Int64, FixedPointNumbers.N0f8})
    @ Base ./promotion.jl:374
  [3] not_sametype(x::Tuple{Int64, FixedPointNumbers.N0f8}, y::Tuple{Int64, FixedPointNumbers.N0f8})
    @ Base ./promotion.jl:368
  [4] promote
    @ ./promotion.jl:351 [inlined]
  [5] <(x::Int64, y::FixedPointNumbers.N0f8)
    @ Base ./promotion.jl:419
  [6] >(x::FixedPointNumbers.N0f8, y::Int64)
    @ Base ./operators.jl:378
  [7] (::var"#1#2")(x::ColorTypes.RGBX{FixedPointNumbers.N0f8})
    @ Main ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:22
  [8] iterate
    @ ./generator.jl:47 [inlined]
  [9] _collect
    @ ./array.jl:744 [inlined]
 [10] collect_similar(cont::Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}}, itr::Base.Generator{Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}}, var"#1#2"})
    @ Base ./array.jl:653
 [11] map(f::Function, A::Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}})
    @ Base ./abstractarray.jl:2867
 [12] initalize_model(map_url::String)
    @ Main ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:22
 [13] top-level scope
    @ ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:46
in expression starting at /Users/weili/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:46
```

### LINKED ISSUE #21: Use `@agent` in all examples
Instead of manually creating a `mutable struct`!

### LINKED ISSUE #22: Video of "Ants" example doesn't load in the examples zoo doc page
I noticed that the video for the "Ants" example doesn't load in the doc. However, the video loads correctly on the main documentation page of `agents.jl`.

### PR DESCRIPTION
**Pull request by ameligrana**
Closes #21 , Closes #22, Closes #13 

There is still probably something to do, and I still didn't run the examples locally so surely there are some mistakes

### CODE REVIEW

**Comment by Datseris** [comment]
That's okay, we anyways have some time to wrap up v6. I have to do the Gillespie PR.

**Comment by Tortar** [comment]
Still not working properly:

- forest fire
- game of life
- growing bacteria
- battle

**Comment by ameligrana** [comment]
Everything now works locally

**Comment by ameligrana** [comment]
Apart from some errors due to that bug I fixed in the PR I opened in Agents, there are some

```julia
 ┌ Error: Cannot resolve @ref for '@agent' in src/examples/runners.md.
│ - no doc found for reference '[`@agent`](@ref)' in src/examples/runners.md.
│   node =
│    @ast MarkdownAST.Link("@ref", "") do
│      MarkdownAST.Code("@agent")
│    end
│    
└ @ Documenter ~/.julia/packages/Documenter/2OZOh/src/utilities/utilities.jl:44
```

for many reference to Agents functions, do you maybe know how to resolve them @Datseris ?

**Comment by ameligrana** [comment]
everythings works!!

**Pull request merged**
