### PR TITLE
Add exportable models to the package

### PR DESCRIPTION
**Pull request by ameligrana**
For https://github.com/JuliaDynamics/Agents.jl/pull/939

@fbanning let me know what do you think about this :-)

We should then release this package to make it usable from `Agents` I guess

### CODE REVIEW

**Comment by Datseris** [comment]
what a great idea to have this as package offering predefined models! Sorry that I haven't followed the discussion so far. But I definitely fully agree with the plan!

Here's the setup I propose:

- No names are exported. All names therefore accessed as `AgentsExampleZoo.function_name`.
- Functions are named as models and return an instance of the ABM and nothing else. In v6 where the dynamic rule is included we don't need anything else.
- The examples say at the top something like "this model is predefined and can be accessed like `AgentsExampleZoo.name()`.

**Comment by ameligrana** [comment]
seems very good to me, do we then want to make all models in this repo like so? It seems to me something useful for any model actually, even the ones we will not test in Agents.jl

One cool thing I thought about (even if it is actually outside the scope of this pr) is to reduce the code duplication of examples all over the places: I don't know much about Documenter.jl but it would be cool to have the definition of the models inside the repo and then use some documentation magic to re-paste the code when used in the tutorial. This way we remove code duplication which can be a source of sync mistakes.

**Comment by Datseris** [comment]
Doing it for all models is fine but can take effort so I would let it as open issue for beginners contributors.

For the second half, unfortunately I do not know of a way from the top of my head...

**Comment by ameligrana** [comment]
I guess it's okay as it is now, we have only `daisyworld` example in the repo so I applied the info about the predefined model just there.

The docs are not building though

**Pull request merged**
