### PR TITLE
Use `walk!` in bacterial growth

### PR DESCRIPTION
**Pull request by MichielStock**
in response to #8

### CODE REVIEW

**Comment by Datseris** [comment]
thanks. we should fix #5 in this PR. Can you run the example without errors locally?

**Comment by MichielStock** [comment]
It generates the movie without any problems.

**Comment by Datseris** [comment]
@MichielStock can you please upload the movie here? I really can't get this to work locally and i'm trying to identify the problem.

**Comment by Datseris** [comment]
Sorry, forget what I wrote! I've fixed it!!!

**Pull request merged**
